#!/bin/bash
# Set up the systemd unit. Requires root.

# Make sure we are running where we think we are.
if [ ! -e misc/leapd.service ]; then
  echo "This script should be run in the root directory of the repo, where you can see the misc/ and scripts/ directories."
  exit 1
fi

# Place the unit file.
mkdir -p /etc/systemd/system
cp misc/leapd.service misc/leapd-resume.service /etc/systemd/system

# Tell systemd that it is there.
systemctl daemon-reload

# Enable it to start on boot.
systemctl enable leapd
systemctl enable leapd-resume

# Start it now. Disabled to give clarity on where things went wrong if things didn't go according to plan.
#systemctl start leapd
